research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year} not more then 50 words.
  expected_output: >
    A list with 1 bullet points of the most relevant information about {topic} not more then 50 words
  agent: researcher

reporting_task:
  description: >
    Review the context you got.
    Make sure the report is brief, consice and small and relevant information.
  expected_output: >
    A report with the main topics not more then 50 words.
    Formatted as markdown without '```'
  agent: reporting_analyst
