product_finder_agent_task:
  description: >
     {user_query}
  expected_output: >
    Fatch the  data from knowledge  {user_query}, return the result in printable format like:\\n1: [product_id=product_id,model_name, company,
    brand, type, price and discount] always use this format to reply. dont think of your own, dont search on web.
  agent: product_finder_agent

check_out_agent_task:
  description: >
    {user_query}
  expected_output: >
     {user_query} .
     dont think of your own, dont search on web. 
  agent: check_out_agent

