# manager_agent_task:
#   description: >
#     Evaluate incoming inquiries and delegate them to the appropriate  Agent. {user_query}. Dont do any search on web
#     or knowledge base for this task by your own, do not think of your own, just delegate it to the right agent and get response from him 
#   expected_output: >
#     tasks are assigned to the most suitable  Agent. {user_query} .
#   agent: manager_agent

product_finder_agent_task:
  description: >
    Fatch the data from knowledge RAG {user_query}
  expected_output: >
    Fatch the  data from knowledge RAG {user_query}, dont think of your own, dont search on web.
  agent: product_finder_agent
