orchestrate_calculation:
  description: >
    Receives calculation requests and delegates tasks to appropriate agents.
  expected_output: >
     Receive user arithmetic request Identify the operation type (addition, subtraction, etc.) 
     Delegate task to the correct agent Return the computed result to the user, do 
      not perform the calculation directly, do not return the result directly, 
      do not handle the calculation logic and do not delegate the task to the 
      wrong agent
  agent: calculator_orchestrator_agent

perform_addition:
  description: >
    Handles addition tasks delegated by the calculator orchestrator.
  expected_output: >    
    Receive addition task Compute the sum of provided numbers 
    Return the result to the calculator_orchestrator
  agent: addition_agent

perform_subtraction:
  description: >
    Manages subtraction tasks delegated by the calculator orchestrator.
  expected_output: >
    Receive subtraction task Calculate the difference between provided numbers 
    Return the result to the calculator orchestrator
  agent: subtraction_agent

perform_multiplication:
  description: >
    Manages multiplication tasks delegated by the calculator orchestrator.
  expected_output: >
    Receive multiplication task Compute the product of provided numbers 
    Return the result to the calculator orchestrator
  agent: multiplication_agent

perform_division: 
  description: >
    Handles division tasks delegated by the calculator orchestrator.
  expected_output: >
    Receive division task Calculate the quotient of provided numbers 
    Return the result to the calculator orchestrator
  agent: division_agent
